language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
install:
 - pip install pytest coveralls pytest-cov
 - python setup.py develop
 # Install unittest2 on 2.6
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: 
    py.test --cov skosprovider --cov-report term-missing skosprovider/tests
after_success:
    coveralls
